<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;


class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        $date = Carbon::now(new \DateTimeZone('AMERICA/Monterrey'));
        DB::table('status_catalog')->insert([
            ['id' => 0,'name' => 'Cancelado', 'table' => 'tickets'],
            ['id' => 1,'name' => 'Aprobado', 'table' => 'tickets'],
            ['id' => 2,'name' => 'Revisando', 'table' => 'tickets'],
            ['id' => 3,'name' => 'revisando', 'table' => 'refers'],
            ['id' => 4,'name' => 'Cancelado', 'table' => 'refers'],
            ['id' => 5,'name' => 'Aprobado', 'table' => 'refers'],
            ['id' => 6,'name' => 'Aprobado', 'table' => 'extrapointValue'],
            ['id' => 7,'name' => 'Cancelado', 'table' => 'app_share'],
            ['id' => 8,'name' => 'Aprobado', 'table' => 'app_share'],
            ['id' => 9,'name' => 'Revisando', 'table' => 'app_share'],
            ['id' => 10,'name' => 'Cancelado', 'table' => 'trivia_score'],
            ['id' => 11,'name' => 'Aprobado', 'table' => 'trivia_score'],
            ['id' => 12,'name' => 'Pendiente', 'table' => 'trivia_score'],
            ['id' => 13,'name' => 'Revisando', 'table' => 'trivia_score'],
            ['id' => 14,'name' => 'Activo', 'table' => 'trivia_questions'],
            ['id' => 15,'name' => 'Inactivo', 'table' => 'trivia_questions'],
            ['id' => 16,'name' => 'Correcta', 'table' => 'trivia_answers'],
            ['id' => 17,'name' => 'Incorrecta', 'table' => 'trivia_answers'],
            ['id' => 18,'name' => 'Activo', 'table' => 'users'],
            ['id' => 19,'name' => 'Inactivo', 'table' => 'users'],
            ['id' => 20,'name' => 'Cancelado', 'table' => 'minigame_score'],
            ['id' => 21,'name' => 'Aprobado', 'table' => 'minigame_score'],
            ['id' => 22,'name' => 'Pendiente', 'table' => 'minigame_score'],
            ['id' => 23,'name' => 'Revisando', 'table' => 'minigame_score'],
            ['id' => 24,'name' => 'Activa', 'table' => 'promo'],
            ['id' => 25,'name' => 'Inactiva', 'table' => 'promo'],
            ['id' => 26,'name' => 'En stock', 'table' => 'awards'],
            ['id' => 27,'name' => 'Sin stock', 'table' => 'awards'],
            ['id' => 28,'name' => 'Activa', 'table' => 'popUp'],
            ['id' => 29,'name' => 'Inactivo', 'table' => 'popUp'],
            ['id' => 30,'name' => 'Activo', 'table' => 'bonus'],
            ['id' => 31,'name' => 'Inactivo', 'table' => 'bonus'],
            ['id' => 32,'name' => 'Pending_Valid', 'table' => 'extrapointValue'],
            ['id' => 33,'name' => 'Active', 'table' => 'presentation_not_arca'],
            ['id' => 34,'name' => 'Inactive', 'table' => 'presentation_not_arca'],
            ['id' => 35,'name' => 'Pending valid', 'table' => 'orders'],
            ['id' => 36,'name' => 'Valid', 'table' => 'orders'],
            ['id' => 37,'name' => 'Cancel', 'table' => 'orders'],
            ['id' => 38,'name' => 'Promoción terminada', 'table' => 'promo'],
            ['id' => 39,'name' => 'En camino', 'table' => 'orders'],
            ['id' => 40,'name' => 'Entregado', 'table' => 'orders'],
            ['id' => 41,'name' => 'enable', 'table' => 'presentation'],
            ['id' => 42,'name' => 'disable', 'table' => 'presentation'],
            ['id' => 43,'name' => 'delete', 'table' => 'presentation'],
            ['id' => 44,'name' => 'enable', 'table' => 'adminUsers'],
            ['id' => 45,'name' => 'disable', 'table' => 'adminUsers'],
            ['id' => 46,'name' => 'invalid', 'table' => 'tickets'],
        ]);

        DB::table('type_catalog')->insert([
            ['name' => 'refer', 'table' => 'extra_pointValue', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'miniGames', 'table' => 'extra_pointValue', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'app_share', 'table' => 'extra_pointValue', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'tienda', 'table' => 'promo', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'carrera', 'table' => 'promo', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'bonus', 'table' => 'bonus', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'ingresos', 'table' => 'transactions', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'egresos', 'table' => 'transactions', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'rifas', 'table' => 'promo', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'Opción mútiple', 'table' => 'questions', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
            ['name' => 'Pregunta libre', 'table' => 'questions', 'created_at' => Carbon::now() , 'updated_at' => Carbon::now()],
        ]);

        // DB::table('awards')->insert([
        //     'promo_id' => 1,
        //     'image' => 'a',
        //     'name' => 'Gift card Amazon',
        //     'description' => 'Hola',
        //     'stock' => 400,
        //     'redeem' => 0,
        //     'price' => 100,
        //     'status_id' => 2,
        //     'created_at' => $date,
        //     'updated_at' => $date,
        // ]);

        DB::table('states')->insert([
            ['name' => 'Baja California Norte', 'promo_id' => 1],
            ['name' => 'Sonora', 'promo_id' => 1],
            ['name' => 'Chihuahua', 'promo_id' => 1],
            ['name' => 'Baja California Sur', 'promo_id' => 1],
            ['name' => 'Coahuila', 'promo_id' => 1],
            ['name' => 'Sinaloa', 'promo_id' => 1],
            ['name' => 'Durango', 'promo_id' => 1],
            ['name' => 'Nuevo León', 'promo_id' => 1],
            ['name' => 'Zacatecas', 'promo_id' => 1],
            ['name' => 'Tamaulipas', 'promo_id' => 1],
            ['name' => 'San Luis Potosí', 'promo_id' => 1],
            ['name' => 'Aguascalientes', 'promo_id' => 1],
            ['name' => 'Jalisco', 'promo_id' => 1],
        ]);

        DB::table('admin_users')->insert([
            [
                'name' => 'Ivan',
                'email' => 'pruebas@sysop.com',
                'password' => md5('Ivan12345'),
                'type_id' => 1,
                'status_id' => 44,
                'created_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')),
                'updated_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey'))
            ],
            [
                'name' => 'Aldo',
                'email' => 'aldog@editasolutions.com.mx',
                'password' => md5('Aldog123'),
                'type_id' => 1,
                'status_id' => 44,
                'created_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')),
                'updated_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey'))
            ],
            [
                'name' => 'Victor',
                'email' => 'victor@editasolutions.com.mx',
                'password' => md5('Victor123'),
                'type_id' => 1,
                'status_id' => 44,
                'created_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')),
                'updated_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey'))
            ],
            [
                'name' => 'Mayra',
                'email' => 'mayra@editasolutions.com.mx',
                'password' => md5('Mayra_22'),
                'type_id' => 1,
                'status_id' => 44,
                'created_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')),
                'updated_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey'))
            ],
        ]);

        DB::table('promo')->insert([
            ['title' => 'Soccer FAN', 'begin_date' => '2022-06-25', 'end_date' => '2022-08-22', 'type_id' => 1, 'imageBanner' => 'img/promo/promo1/promo1.png', 'image' => 'img/promo/promo1/promo1.png',
            'status_id' => 24, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('video_global')->insert([
            [
                'pathVideo' => 'https://player.vimeo.com/video/710821757?h=fb98593299',
                'promo_id' => 1,
                'type' => 'steps',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'pathVideo' => 'https://player.vimeo.com/video/710821820?h=d0743a7906',
                'promo_id' => 1,
                'type' => 'awards',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'pathVideo' => 'https://player.vimeo.com/video/710821855?h=20f4cbc991',
                'promo_id' => 1,
                'type' => 'promo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],


        ]);

        DB::table('periods')->insert([
            ['promo_id' => 1, 'order' => 1, 'inicial_date' => '2022-06-25 00:00:00', 'final_date' => '2022-08-22 00:00:00'],
        ]);


        DB::table('messages')->insert([
            [
                'section' => 'campaign',
                'title' => 'main',
                'content' => 'Hola',
                'created_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')) ,
                'updated_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey'))
            ],
        ]);

        DB::table('campaign')->insert([
            [
                'slug' => 'slug1Example',
                'description' => 'Slug de prueba 1',
                'visitors' => 0,
                'registers' => 0,
                'created_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')),
                'updated_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')),
            ],
        ]);


        DB::table('versions')->insert([
            'num_version' => '1.0.0',
            'created_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey')) ,
            'updated_at' => Carbon::now(new \DateTimeZone('AMERICA/Monterrey'))
        ]);

        DB::table('type_presentation')->insert([
            ['name' => 'Snacks'],
            ['name' => 'Basico'],
            ['name' => 'Bebidas'],
            ['name' => 'Varios'],
        ]);

        DB::table('presentation')->insert([
            ['promo_id' => 1, 'name' => 'T CH HARD S FRESA- 355 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'T CH HARD S LIMA L 355 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'T CH HARD S PIÑA T 355 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL MINERALIZADA 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL MINERALIZADA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'T CH AGUA MINERAL 1.50 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'T CH AGUA MINERAL 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'T CH TWIST LIMÓN 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'T CH TWIST TORONJA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL AGUA PURIF 1.00 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL AGUA PURIF 1.50 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL AGUA PURIF 5.00 L' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL AGUA PURIF 600 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL EXPRIM FRESA 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL EXPRIM JAMAIC 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL EXPRIM LIMON 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'VITAMIN W ENERGY 500 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'VITAMIN W POWERC 500 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'ADES FRUTAL MANGO 200 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'ADES FRUTAL MANZAN 200 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'ADES FRUTAL MANZAN 946 ML' ,'pointValue' => 3, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'ADES LÁCTEO NATURA 946 ML' ,'pointValue' => 3, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRUTSI FRUTAS ROJA 250 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRUTSI UVA 250 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DELAWARE PUNCH UVA 355 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DELAWARE PUNCH UVA 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DELAWARE PUNCH UVA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'PULPY NARANJA 400 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 1.00 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 1.25 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 1.50 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 235 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 3.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 473 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 500 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 500 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 500 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 600 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA 710 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CC CAFÉ CARAMELO 235 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CC CAFÉ EXPRESSO 235 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CC CAFÉ VAINILLA 235 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA COLA SIN AZÚC 1.00 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA COLA SIN AZÚC 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA COLA SIN AZÚC 235 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA COLA SIN AZÚC 235 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA COLA SIN AZÚC 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA COLA SIN AZÚC 500 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA COLA SIN AZÚC 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 1.00 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 235 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 500 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'COCA-COLA LIGHT 600 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'MONSTER ENERGY ORI 473 ML NR' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'CIEL AGUA PURIF 20.0 L' ,'pointValue' => 1, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE FRUT ROJA 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE FRUT ROJA 500 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE FRUT ROJA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE LIMALIM 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE LIMALIM 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE MORAS 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE MORAS 500 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE MORAS 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE NARMAND 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE NARMAND 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE UVA 500 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'POWERADE UVA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE DURAZNO 250 ML' ,'pointValue' => 40, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE DURAZNO 335 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE DURAZNO 413 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE DURAZNO 946 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE GUAYABA 413 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE MANGO 413 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE MANZANA 250 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE MANZANA 335 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE MANZANA 413 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE NC MANZ 250 ML' ,'pointValue' => 40, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE NC MANZ 413 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE NC MANZ 500 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE NC MANZ 946 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE PIÑA 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DEL VALLE PIÑA 335 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DVALLE RESERVA ARÁ 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SCL LECHE DESLAC 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SCL LECHE ENTERA 1.00 L' ,'pointValue' => 2, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SCL LECHE ENTERA 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SCL LECHE LIGHT 1.00 L' ,'pointValue' => 2, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SCL LECHE LIGHT 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SCL LECHE FRESA 200 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SCL LECHE VAINILLA 200 ML' ,'pointValue' => 4, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'VALLE FRUT CITRUS 1.00 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'VALLE FRUT CITRUS 1.50 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'VALLE FRUT CITRUS 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'VALLE FRUT CITRUS 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'VALLE FRUT CITRUS 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DVALLE Y NADA LIMO 1.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DVALLE Y NADA NARA 1.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DVALLE Y NADA NARA 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'DVALLE Y NADA NARA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA FRESA 2.00 L NR' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA FRESA 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 1.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 3.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 400 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FANTA NARANJA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 1.00 L' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 1.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 1.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 3.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 355 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 400 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FRESCA TORONJA 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SIDRAL MUN MZA-DZO 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SIDRAL MUNDET MANZ 1.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SIDRAL MUNDET MANZ 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SIDRAL MUNDET MANZ 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SIDRAL MUNDET MANZ 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SIDRAL MUNDET MANZ 400 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SIDRAL MUNDET MANZ 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 1.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 2.00 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 2.50 L' ,'pointValue' => 8, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 3.00 L' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 355 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 355 ML' ,'pointValue' => 24, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 400 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 400 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'T CH SANGRIA 600 ML' ,'pointValue' => 12, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'SPRITE SIN AZÚCAR 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FUZE TEA DURAZNO 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FUZE TEA NEGRO LIM 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],
            ['promo_id' => 1, 'name' => 'FUZE TEA VERDE LIM 600 ML' ,'pointValue' => 6, 'created_at' => $date, 'updated_at' => $date, 'status_id' => 42],

        ]);

        DB::table('presentation_not_arca')->insert([
            ['typePresentation_id' => 1,'name' => 'Frituras', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 1,'name' => 'Cacahuates', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 1,'name' => 'Pan dulce embolsado', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 1,'name' => 'Pan dulce', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 1,'name' => 'Chocolates', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 1,'name' => 'Palomitas', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 1,'name' => 'Otros', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 2,'name' => 'Leche otras marcas', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 2,'name' => 'Pan de barra', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 2,'name' => 'Tortillas', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 2,'name' => 'Huevo', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 2,'name' => 'Otros', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 3,'name' => 'Pepsi', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 3,'name' => 'Otras Marcas', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 3,'name' => 'Agua Otras Marcas', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 3,'name' => 'Cerveza', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 3,'name' => 'Licores', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 3,'name' => 'Otras', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 4,'name' => 'Cigarros', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 4,'name' => 'Carbon', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 4,'name' => 'Medicamentos', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 4,'name' => 'Articulos de Limpieza', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 4,'name' => 'Articulos de higiene', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
            ['typePresentation_id' => 4,'name' => 'Otros', 'status_id' => 33, 'promo_id' => 1, 'created_at' => $date, 'updated_at' => $date],
        ]);


        // Insert Quiz
        DB::table('mini_games')->insert([
            ['title' => 'Quiz','created_at' => $date, 'updated_at' => $date]
        ]);

        DB::table('quizzes')->insert([
            ['title' => 'Juego contra reloj','type_id' => 1,'promo_id' => 1,'created_at' => $date, 'updated_at' => $date]
        ]);

        DB::table('questions')->insert([
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>1,'title'=>'Hubo dos trofeos para la Copa del Mundo. ¿Cómo se llamaba el primero?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>2,'title'=>'¿Qué selección ganó la primera Copa del Mundo (1930)?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>3,'title'=>'¿Qué selección tiene más títulos en la Copa del Mundo?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>4,'title'=>'Tres selecciones han ganado la Copa del Mundo en dos ocasiones. ¿Puedes nombrarlas?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>5,'title'=>'¿Qué selección llegó a tres finales de la Copa del Mundo pero nunca ganó el título?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>6,'title'=>'La Copa del Mundo de 2026 se jugará en tres países diferentes. ¿Puedes nombrarlos?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>7,'title'=>'¿En qué Copa del Mundo Diego Maradona firmó la famosa Mano de Dios?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>8,'title'=>'¿Cuántos goles anoto Péle en durante los mundiales en los que participo?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>9,'title'=>'Tres personas ganaron la Copa del Mundo como jugadores y como técnicos: Mario Zagallo, Didier Deschamps y... ¿quién más?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>10,'title'=>'¿Cuándo tuvo lugar la primera Copa Mundial de Fútbol?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>11,'title'=>'¿Qué animal fue el escogido para ilustrar la mascota del Mundial de Rusia?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>12,'title'=>'¿Cómo se llamaba la mascota del mundial de Rusia?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>13,'title'=>'¿Comó se llamaba la mascota del mundial de españa en 1982?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>14,'title'=>'¿Cómo se llamaba la macota del mundial de Francia en 1988?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>15,'title'=>'¿Cómo se llamaba la mascota del mundial de Brasil 2014?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>16,'title'=>'¿A qué futbolista se conoce con el apodo de Harry Potter?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>17,'title'=>'¿Dónde tendrá lugar la copa mundial en 2022?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>18,'title'=>'¿Quién fabrica el balon con el que se jugara Qatar 2022?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>19,'title'=>'¿Cuántos mundiales de fútbol ha ganado España?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>20,'title'=>'¿A quen se enfrento españa cuando gano su primer y unico mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>21,'title'=>'¿Recuerdas dónde se jugó la Copa del Mundial del año 2010?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>22,'title'=>'¿Por qué no se disputo el mundial en 1942?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>23,'title'=>'¿Cuántos mundiales se han disputado en Europa?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>24,'title'=>'¿Cuántos mundiales se han disputado en Amercia?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>25,'title'=>'¿Cuántos mundiales se han disputado en el continente africano?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>26,'title'=>'¿Cuál fue la primer sede del mundial en 1930?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>27,'title'=>'¿Qué equipo ganó el mundial en 1986?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>28,'title'=>'¿En donde se celebro el mundial en el año de 1986?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>29,'title'=>'¿Cuál es el equipo con más partidos jugados durante los mundiales?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>30,'title'=>'¿Qué equipo ha ido a todos los mundiales desde su inauguracion?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>31,'title'=>'¿Cuál fue la peor goleada durante un mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>32,'title'=>'¿Cuál es el unico pais latinoamericano que ha ganado un titulo de campeon en un mundial jugado en europa? '],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>33,'title'=>'¿Quién es el jugador latino que ha anotado más goles en la historia de los mundiales?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>34,'title'=>'¿Qué jugador es conocido como “la mano de Dios”?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>35,'title'=>'¿Quién fue el goleador del primer mundial de fútbol? '],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>36,'title'=>'¿Cómo se le llamó a la famosa victoria de Uruguay sobre Brasil en 1950?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>37,'title'=>'¿Quién fue el primer jugador que metio un gol en el mundial de 1930?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>38,'title'=>'¿En que años México organizo la copa mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>39,'title'=>'¿Qué pais tuvo que reununciar a ser sede del mundial en 1986?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>40,'title'=>'¿A quien le llaman el cinco copas por sus 5 participaciones en mundiales?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>41,'title'=>'¿En que año participo la selección de futbol de Cuba en una copa del mundo?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>42,'title'=>'¿Quién ha ganado el mundial como entrenador y como jugador?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>43,'title'=>'¿Qué jugador ha ganado el mundial en tres ocasiones? '],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>44,'title'=>'¿En que país se jugo el primer mundial despues de la segunda guerra mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>45,'title'=>'¿Qué día inicia la copa del mundo en 2022?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>46,'title'=>'¿Dónde sera la final del mundo en el 2022?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>47,'title'=>'¿En donde fue la sede del mundial en 1934?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>48,'title'=>'¿En donde fue la sede del mudnial de 1950?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>49,'title'=>'¿En que año fue sede Estados Unidos de la Copa mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>50,'title'=>'¿En donde fue la sede del mundial en 1978?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>51,'title'=>'¿En que año fue sede del mundial Japón?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>52,'title'=>'¿En donde fue la sede del mundial del 2018?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>53,'title'=>'¿Cuál es el equipo con más expulsiones desde que se implemento el mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>54,'title'=>'¿En que ciudad fue la final del mundial de Brasil 2014?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>55,'title'=>'¿quién fue el primer portero en un mundial en usar guantes?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>56,'title'=>'¿Qué país por primera vez en su historia no logró superar la fase de grupos en un mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>57,'title'=>'¿cuántos equipos en total participan en una copa del mundo?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>58,'title'=>'¿Cuál fue el primer mundial en el que aparecen las mascotas?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>59,'title'=>'¿En que mundial se usan por primera vez las tarjetas amarillas?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>60,'title'=>'¿En que mundial se permite por primera vez la sustitucion de jugadores?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>61,'title'=>'¿Cuál fue el primer mundial en televisarse a color?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>62,'title'=>'¿En que mundial aparece por primera vez la ola en los estadios?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>63,'title'=>'¿cuatas veces México no ha ido a un mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>64,'title'=>'¿En que mundial por primera vez una final termina 0-0?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>65,'title'=>'¿En que sede del mundial por primera vez la organización recae sobre dos paises conjuntamente?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>66,'title'=>'¿Jugador Méxicano con mas partidos jugados en un mundial?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>67,'title'=>'¿En que año gano Brasil su primera copa del mundo?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>68,'title'=>'¿En que mundial por primera vez el equipo organizador no pasa la primera fase?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>69,'title'=>'¿Quién fue el ganador de la compa mundial México 1986?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>70,'title'=>'¿Qué premio se otorga cada mundial al jugador más destacado?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>71,'title'=>'¿Cuál ha sido considerado el mejor mundial de futbol de la historia?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>72,'title'=>'¿Dónde se celebro el mundial de 1954?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>73,'title'=>'¿Quién era el portero titular de Italia en el Mundial 82?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>74,'title'=>'¿Quién ganó el Mundial de 1950 celebrado en Brasil?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>75,'title'=>'¿Qué jugador marcó el gol decisivo en la final del Mundial 2010?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>76,'title'=>'¿Contra qué equipo marcó Maradona su célebre gol con la mano en el Mundial de 1986?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>77,'title'=>'¿Dónde se celebro el mundial de 1962?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>78,'title'=>'¿Cuántos goles marcó el "Chicharito" Hernández en el mundial de 2014?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>79,'title'=>'¿En qué Mundial ganó México su primer partido en los mundiales?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>80,'title'=>'¿Cuántos y qué mundiales ha jugado Hugo Sánchez?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>81,'title'=>'¿Contra qué equipo jugó México su primer partido en la historia de los mundiales?'],
            ['created_at' => $date,'quiz_id'=>1,'type_id' => 10,'order'=>82,'title'=>'¿Quién era el portero titular de la selección mexicana en el Mundial de Francia 1998?'],
        ]);

        DB::table('question_answers')->insert([
            ['question_id' => 1 , 'answer'=> 'Trofeo Jules Klose', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 1 , 'answer'=> 'Trofeo Jules Rimet', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 1 , 'answer'=> 'Trofeo Copa Kane', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 2 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 2 , 'answer'=> 'Uruguay', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 2 , 'answer'=> 'Holanda', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 3 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 3 , 'answer'=> 'Holanda', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 3 , 'answer'=> 'Brasil', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 4 , 'answer'=> 'Francias, México, Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 4 , 'answer'=> 'Argentina, Francia y Uruguay', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 4 , 'answer'=> 'Italia, Argentina, Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 5 , 'answer'=> 'Holanda', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 5 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 5 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 6 , 'answer'=> 'Estados Unidos, Venezuela, Colombia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 6 , 'answer'=> 'Estados Unidos, México, Canadá', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 6 , 'answer'=> 'Francia, Inglaterra, España', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 7 , 'answer'=> 'Italia 90', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 7 , 'answer'=> 'México 86', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 7 , 'answer'=> 'Francia 98', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 8 , 'answer'=> '9', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 8 , 'answer'=> '12', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 8 , 'answer'=> '3', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 9 , 'answer'=> 'Jules Rimet', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 9 , 'answer'=> 'Harry Kane', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 9 , 'answer'=> 'Franz Beckenbauer', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 10 , 'answer'=> '1940', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 10 , 'answer'=> '1930', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 10 , 'answer'=> '1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 11 , 'answer'=> 'Un lobo', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 11 , 'answer'=> 'Un perro', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 11 , 'answer'=> 'Un gato', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 12 , 'answer'=> 'Lucho', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 12 , 'answer'=> 'Perrón', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 12 , 'answer'=> 'Zabivaka', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 13 , 'answer'=> 'Azulito', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 13 , 'answer'=> 'Naranjito', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 13 , 'answer'=> 'Moradito', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 14 , 'answer'=> 'Kira', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 14 , 'answer'=> 'Robi', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 14 , 'answer'=> 'Footix', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 15 , 'answer'=> 'Perruno', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 15 , 'answer'=> 'Fuleco', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 15 , 'answer'=> 'Baracilio', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 16 , 'answer'=> 'Luis Arturo Hernández Carreón', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 16 , 'answer'=> 'Ricardo Quaresma', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 16 , 'answer'=> 'Diego Maradona', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 17 , 'answer'=> 'Qatar', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 17 , 'answer'=> 'Suiza', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 17 , 'answer'=> 'Islandia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 18 , 'answer'=> 'Soriana', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 18 , 'answer'=> 'Adidas', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 18 , 'answer'=> 'Innova Sport', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 19 , 'answer'=> '4', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 19 , 'answer'=> '2', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 19 , 'answer'=> '1', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 20 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 20 , 'answer'=> 'Holanda', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 20 , 'answer'=> 'Estados Unidos', 'correct_answer'=> 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 21 , 'answer'=> 'Italia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 21 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 21 , 'answer'=> 'Sudáfrica', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 22 , 'answer'=> 'Por la guerra de las malvinas', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 22 , 'answer'=> 'Por la segunda guerra mundial', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 22 , 'answer'=> 'Por la caida del muro de Berlín', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 23 , 'answer'=> '9', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 23 , 'answer'=> '6', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 23 , 'answer'=> '3', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 24 , 'answer'=> '9', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 24 , 'answer'=> '5', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 24 , 'answer'=> '3', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 25 , 'answer'=> '1', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 25 , 'answer'=> '4', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 25 , 'answer'=> '7', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 26 , 'answer'=> 'España', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 26 , 'answer'=> 'Uruguay', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 26 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 27 , 'answer'=> 'Italia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 27 , 'answer'=> 'Francia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 27 , 'answer'=> 'Argentina', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 28 , 'answer'=> 'Alemania', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 28 , 'answer'=> 'México', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 28 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 29 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 29 , 'answer'=> 'Alemania', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 29 , 'answer'=> 'España', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 30 , 'answer'=> 'Brasil', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 30 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 30 , 'answer'=> 'Estados Unido', 'correct_answer'=> 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 31 , 'answer'=> 'Brasil 15-0 Perú', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 31 , 'answer'=> 'Ungria 10-1 Salvador', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 31 , 'answer'=> 'Alemania 7-0 Italia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 32 , 'answer'=> 'Brasil', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 32 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 32 , 'answer'=> 'Venezuela', 'correct_answer'=> 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 33 , 'answer'=> 'Ronaldo Nazario de Lima', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 33 , 'answer'=> 'Diego Armando Maradona', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 33 , 'answer'=> 'Pelé', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 34 , 'answer'=> 'Péle', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 34 , 'answer'=> 'Diego Armando Maradona', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 34 , 'answer'=> 'Ronaldo Nazario', 'correct_answer'=> 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 35 , 'answer'=> 'Bigodes', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 35 , 'answer'=> 'Guillermo Stabile', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 35 , 'answer'=> 'Péle', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 36 , 'answer'=> 'El triunfo del siglo', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 36 , 'answer'=> 'El Maracanazo', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 36 , 'answer'=> 'El chutazo', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 37 , 'answer'=> 'Vincet Lux', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 37 , 'answer'=> 'Rolando Miller', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 37 , 'answer'=> 'Lucien Lauent', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 38 , 'answer'=> '1930 y 1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 38 , 'answer'=> '1982 y 1986', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 38 , 'answer'=> '1970 y 1986', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 39 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 39 , 'answer'=> 'Argentina', 'correct_answer' => 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 39 , 'answer'=> 'Colombia', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 40 , 'answer'=> 'Javier Zanetti', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 40 , 'answer'=> 'Antonio “La Tota” Carbajal', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 40 , 'answer'=> 'Hugo Sanchez', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 41 , 'answer'=> 'Francia 1938', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 41 , 'answer'=> 'Suiza 1954', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 41 , 'answer'=> 'Uruguay 1930', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 42 , 'answer'=> 'Hugo Sanchez', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 42 , 'answer'=> 'Mário Zagallo', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 42 , 'answer'=> 'Javier Zanetti', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 43 , 'answer'=> 'Maradona', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 43 , 'answer'=> 'Pelé', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 43 , 'answer'=> 'Miller', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 44 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 44 , 'answer'=> 'Brasil', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 44 , 'answer'=> 'Estados Unido', 'correct_answer'=> 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 45 , 'answer'=> '11 de octubre', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 45 , 'answer'=> '21 de noviembre', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 45 , 'answer'=> '3 de agosto', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 46 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 46 , 'answer'=> 'Canadá', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 46 , 'answer'=> 'Lusail', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 47 , 'answer'=> 'Uruguay', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 47 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 47 , 'answer'=> 'Italia', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 48 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 48 , 'answer'=> 'Brasil', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 48 , 'answer'=> 'Canadá', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 49 , 'answer'=> '1994', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 49 , 'answer'=> '2006', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 49 , 'answer'=> '2018', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 50 , 'answer'=> 'Argentina', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 50 , 'answer'=> 'México', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 50 , 'answer'=> 'España', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 51 , 'answer'=> '2014', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 51 , 'answer'=> '2002', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 51 , 'answer'=> '1018', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 52 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 52 , 'answer'=> 'Rusia', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 52 , 'answer'=> 'Sudáfrica', 'correct_answer'=> 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 53 , 'answer'=> 'México con 10', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 53 , 'answer'=> 'Estados Unidos con 9', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 53 , 'answer'=> 'Brasil con 11', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 54 , 'answer'=> 'Sao Paulo', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 54 , 'answer'=> 'Rio de Janeiro', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 54 , 'answer'=> 'Fortaleza', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 55 , 'answer'=> 'Lusai Miller', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 55 , 'answer'=> 'Lev Yashin', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 55 , 'answer'=> 'Jaire Swin', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 56 , 'answer'=> 'Perú', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 56 , 'answer'=> 'Nigeria', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 56 , 'answer'=> 'Alemania', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 57 , 'answer'=> '30', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 57 , 'answer'=> '32', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 57 , 'answer'=> '18', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 58 , 'answer'=> 'Inglaterra 1966', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 58 , 'answer'=> 'Mexico 1986', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 58 , 'answer'=> 'Uruguay 1930', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 59 , 'answer'=> 'México 1970', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 59 , 'answer'=> 'Brasil 1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 59 , 'answer'=> 'Uruguay 1930', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 60 , 'answer'=> 'México 1970', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 60 , 'answer'=> 'Brasil 1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 60 , 'answer'=> 'Uruguay 1930', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 61 , 'answer'=> 'Alemania 1974', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 61 , 'answer'=> 'Inglaterra 1966', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 61 , 'answer'=> 'Argentina 1978', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 62 , 'answer'=> 'México 1986', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 62 , 'answer'=> 'Brasil 1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 62 , 'answer'=> 'Italia 1954', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 63 , 'answer'=> '7', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 63 , 'answer'=> '5', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 63 , 'answer'=> '9', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 64 , 'answer'=> 'México 1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 64 , 'answer'=> 'Estados Unidos 1994', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 64 , 'answer'=> 'Italia 1930', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 65 , 'answer'=> 'México / Estados Unidos 1986', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 65 , 'answer'=> 'Japón / Corea 2022', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 65 , 'answer'=> 'Italia /francia 1978', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 66 , 'answer'=> 'Javier Herrera', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 66 , 'answer'=> 'Rafael Marquez', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 66 , 'answer'=> 'Antonio Carbajal', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 67 , 'answer'=> 'México 1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 67 , 'answer'=> 'Italia 1978', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 67 , 'answer'=> 'Suecia 1958', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 68 , 'answer'=> 'México 1986', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 68 , 'answer'=> 'Italia 1954', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 68 , 'answer'=> 'Sudafrica 2010', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 69 , 'answer'=> 'Uruguay', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 69 , 'answer'=> 'Argentina', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 69 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 70 , 'answer'=> 'Pichichi', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 70 , 'answer'=> 'Balón de oro', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 70 , 'answer'=> 'Maracanazo', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 71 , 'answer'=> 'Uruguay 1930', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 71 , 'answer'=> 'Estados Unidos 1954', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 71 , 'answer'=> 'México 1970', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 72 , 'answer'=> 'Austria', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 72 , 'answer'=> 'Suiza', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 72 , 'answer'=> 'Alemania', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 73 , 'answer'=> 'Giancarlo Poll', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 73 , 'answer'=> 'Tacconi', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 73 , 'answer'=> 'Dino Zoff', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 74 , 'answer'=> 'Baril', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 74 , 'answer'=> 'Uruguay', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 74 , 'answer'=> 'Alemania', 'correct_answer'=> 0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 75 , 'answer'=> 'Robben', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 75 , 'answer'=> 'Iniesta', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 75 , 'answer'=> 'Alonso', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 76 , 'answer'=> 'Suencia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 76 , 'answer'=> 'Alemania', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 76 , 'answer'=> 'Inglaterra', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 77 , 'answer'=> 'Argentina', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 77 , 'answer'=> 'Chile', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 77 , 'answer'=> 'Polonia', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 78 , 'answer'=> '3', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 78 , 'answer'=> '4', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 78 , 'answer'=> '1', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 79 , 'answer'=> 'Chile 1962', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 79 , 'answer'=> 'Brasil 1950', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 79 , 'answer'=> 'España 1982', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 80 , 'answer'=> '3', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 80 , 'answer'=> '1', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 80 , 'answer'=> '5', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 81 , 'answer'=> 'Francia', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 81 , 'answer'=> 'Brasil', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 81 , 'answer'=> 'Argentina', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 82 , 'answer'=> 'Oscar Perez', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 82 , 'answer'=> 'Jorge Campos', 'correct_answer'=>1,'created_at' => $date,'updated_at' => $date],
            ['question_id' => 82 , 'answer'=> 'Oswaldo Sanchez', 'correct_answer'=>0,'created_at' => $date,'updated_at' => $date],
        ]);

    }
}
